### ISSUE TITLE
Code Quality: Add package.json

### ISSUE THREAD

**Issue by clinkingdog** [Softwire/Workflowy2Web#4]
Add a package.json file for the project which actually defines all the dependencies and works. You want to be able to install on a machine, run `npm install` then `karma start` and have the tests running.

**Comment by hgcummings** [comment]
Got.

Suggest that the package.json should actually include a test script to launch Karma, so you 'd run ``npm test`` rather than ``karma start`` (it's not possible to globally install karma to the path via ``npm install`` AFAIK)

**Comment by clinkingdog** [comment]
I think SamC already has this one :-)

**Comment by hgcummings** [comment]
Ah, cool, np. I got something quickly working, included below in case it's useful, but feel free to disregard:

```
{
  "name": "workflowy2web",
  "version": "0.1.0",
  "description": "A tool for converting a content outline in Workflowy to a working prototype in HTML",
  "scripts": {
    "test": "node node_modules/karma/bin/karma start --single-run"
  },
  "devDependencies": {
    "karma": "^0.13.15",
    "karma-chrome-launcher": "^0.2.2",
    "karma-jasmine": "^0.3.6"
  }
}
```

Should "just work" if you run ``npm install`` and ``npm test``
